### ISSUE TITLE
Incorrect number of bindings supplied. The current statement uses 4, and there are 5 supplied.

### ISSUE THREAD

**Issue by arkaroy14** [KurimuzonAkuma/pyrogram#101]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

error while upload video
'Incorrect number of bindings supplied. The current statement uses 4, and there are 5 supplied.'
Was working fine till yesterday.

### Steps to reproduce

upload video to private telegram group channel id . username starts with -100

### Code example

```python
client.send_video(chat_id=username, reply_to_message_id=forum_id, video=video_path, caption=caption, progress=progress_callback, thumb=thumbnail_path, duration=int(duration), supports_streaming=True)
```

### Logs

```shell
File "/usr/local/lib/python3.10/dist-packages/pyrogram/storage/sqlite_storage.py", line 145, in update_peers
    self.conn.executemany(
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 4, and there are 5 supplied.
```

**Comment by KurimuzonAkuma** [comment]
Strange, I don't think it's possible to get that error....
https://github.com/KurimuzonAkuma/pyrogram/blob/dev/pyrogram/client.py#L591
https://github.com/KurimuzonAkuma/pyrogram/blob/dev/pyrogram/storage/sqlite_storage.py#L144

Try reinstalling with `pip install https://github.com/KurimuzonAkuma/pyrogram/archive/dev.zip --force-reinstall`.

If that doesn't help, roll back to a stable version using:
`pip install https://github.com/KurimuzonAkuma/pyrogram/archive/v2.1.30.zip --force-reinstall`.

**Comment by arkaroy14** [comment]
Solved after force reinstall. Issue seems to be on my side.
