### ISSUE TITLE
add filters.commands

### ISSUE THREAD

**Issue by m2k7m** [KurimuzonAkuma/pyrogram#103]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

Hi, Can you please add filters.commands
```py
@app.on_message(filters.text & ~filters.commands)
```
this will work for any text that isnt command

**Comment by KurimuzonAkuma** [comment]
Just use regex filter for that...

**Comment by Danstiv** [comment]
What's the use case? Just register the command handlers first.
