### ISSUE TITLE
Unable to Access PyroDocs Wiki and Lost Contact with Organization

### ISSUE THREAD

**Issue by yyned2501** [KurimuzonAkuma/pyrogram#118]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

Hello Team,

I hope this issue finds you well. I'm writing to inform you that I'm currently unable to access the PyroDocs wiki located at [pyrodocs.kurimuzon.ru](http://pyrodocs.kurimuzon.ru/). The site seems to be unreachable, and I'm unsure if it's a temporary outage or something more persistent.

Additionally, I recently faced an issue where my Telegram account was banned. Unfortunately, this has led to me losing access to the group chats where I was previously in touch with the organization. Given this situation, I'm finding it difficult to reconnect with the team or find updated information about the project.

Could you please provide guidance on how I can regain access to the organization's resources or at least get in touch with someone who can help? Any alternative communication channels or steps I can follow would be greatly appreciated.

Thank you for your time and assistance.

Best regards
（The above content was translated from chinese through gpt.）

### Steps to reproduce

none

**Comment by KurimuzonAkuma** [comment]
This is old expired domain. Use docs.kurigram.xyz

**Comment by yyned2501** [comment]
thx
