### ISSUE TITLE
Ответ в бизнес чате

### ISSUE THREAD

**Issue by borborich** [KurimuzonAkuma/pyrogram#37]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

Здравствуйте. Увидел что у вас реализован функционал для бизнес чатов, но ни как не могу понтять как реализовать ответ бота в бизнес чате на подобие такого?

```
@app.on_message()
async def echo(client, message):
    await client.send_message(
        chat_id=message.chat.id,
        text="Привет от бота!"
    )

```

Спасибо если сможете помочь.

**Comment by KurimuzonAkuma** [comment]
хай-лвл для бизнес ботов еще не реализован, пока что в процессе

**Comment by borborich** [comment]
спасибо!

**Comment by KurimuzonAkuma** [comment]
Реализовал поддержку бизнес ботов.

Чтобы бизнес бот отвечал на сообщения нужно добавить его в настройках и запускать клиент через токен бота, уже ему будут прилетать эвенты.

Вот минимальный пример:

```python
from pyrogram import Client

app = Client("bot", api_id, api_hash, bot_token="", in_memory=True)

@app.on_message()
async def echo(client, message):
    await message.reply(
        text="Привет от бота!"
    )

app.run()
```

**Comment by borborich** [comment]
Отлично! спасибо!
