### ISSUE TITLE
Change the docs from pyrogram to yours

### ISSUE THREAD

**Issue by itisFarzin** [KurimuzonAkuma/pyrogram#38]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

Hi, i saw you have your own docs for your fork
it will be great if you link your own docs instead of pyrogram docs in readme
Thanks for keeping pyrogram alive

**Comment by KurimuzonAkuma** [comment]
I won't change the readme, as I expect the main pyrogram developer one day merge my fork

**Comment by ALiwoto** [comment]
![image](https://github.com/KurimuzonAkuma/pyrogram/assets/70187458/40ff645e-a270-45d0-bf12-39d050a686ca)
Well, nothing is impossible; but 309 commits is kind of hard to merge I would say... (still, I hope for it as well)
