### ISSUE TITLE
Question about get_media_group

### ISSUE THREAD

**Issue by reizhi** [KurimuzonAkuma/pyrogram#39]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

In get_media_group.py, a -9 to +10 offset has been set to search media belonging to the same group. But when forwarding a batch of media groups at the same time, each media will come in with different order.

For example, I found a media group that includes these IDs: 466 468 472 476 479, so apparently +10 is not enough. Both Telegram PC and mobile can handle them well, but copy_media_group may fail if the first or the last ID has been used. 

Do we have any better option other than to increase the offset?

**Comment by SpEcHiDe** [comment]
@reizhi can you share an example message link of such a media group, if possible? **i am really curious to see it**
