### ISSUE TITLE
Quotes disappear if you edit message

### ISSUE THREAD

**Issue by APAmk2** [KurimuzonAkuma/pyrogram#51]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

If you add quote to message and then edit it - quote will disappear

### Steps to reproduce

1. Try to edit message, add quote into it
2. Edit it again, just add some text into already existing text, quote will disappear

### Code example

```python
message.edit(text=">" + "quote" + "\n" + message.text)
message.edit(text=message.text + "something")
```

**Comment by SpEcHiDe** [comment]
you have to use

```python
message.edit(text=">" + "quote" + "\n" + message.text)
message.edit(text=message.text.markdown + "something")
```

**Comment by APAmk2** [comment]
Oh, understood, sorry for disturbing.
