### ISSUE TITLE
even @app.on_message(filters.all) cant catch this message

### ISSUE THREAD

**Issue by NimaQu** [KurimuzonAkuma/pyrogram#69]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I am trying to use bot to prevent spam like this, but I can't catch this message using program

link to message: https://t.me/anti_channel_test/350

```
@app.on_message(filters.all)
    async def group_message(client, message):
        logging.info(str(message))
```

Such a message appears in my group and I still can't catch it even with the listed code.
I tried using a bot or a normal account but both not working

### Steps to reproduce

just simply forward this message to the bot https://t.me/anti_channel_test/350

### Code example

```python
@app.on_message(filters.all)
    async def group_message(client, message):
        logging.info(str(message))
```
```


### Logs

_No response_

**Comment by NimaQu** [comment]
message catched by python-telegram-bot:

`(api_kwargs={'forward_date': 1717789016, 'forward_from_chat': {'id': -1002218646183, 'title': '小微', 'username': 'wwwwerrrrww', 'type': 'channel'}}, channel_chat_created=False, chat=Chat(first_name='NimaQu Ch. 白上ニマク |̲̅年̲̅度̲̅大̲̅会̲̅员̲̅|', id=419930440, type=<ChatType.PRIVATE>, username='chacha20_ietf'), date=datetime.datetime(2024, 6, 7, 20, 44, 12, tzinfo=datetime.timezone.utc), delete_chat_photo=False, entities=(MessageEntity(length=6, offset=0, type=<MessageEntityType.BLOCKQUOTE>), MessageEntity(length=6, offset=0, type=<MessageEntityType.BOT_COMMAND>), MessageEntity(length=6, offset=7, type=<MessageEntityType.TEXT_LINK>, url='https://t.me/soso?start=boost_Jijisosuo_1867631521'), MessageEntity(length=4039, offset=13, type=<MessageEntityType.TEXT_LINK>, url='https://t.me/soso?start=boost_coconvn_6257358001'), MessageEntity(length=27, offset=4053, type=<MessageEntityType.BLOCKQUOTE>)), forward_origin=MessageOriginChat(date=datetime.datetime(2024, 6, 7, 19, 36, 56, tzinfo=datetime.timezone.utc), sender_chat=Chat(id=-1002218646183, title='小微', type=<ChatType.CHANNEL>, username='wwwwerrrrww'), type=<MessageOriginType.CHAT>), from_user=User(first_name='NimaQu Ch. 白上ニマク |̲̅年̲̅度̲̅大̲̅会̲̅员̲̅|', id=419930440, is_bot=False, is_premium=True, language_code='zh-hans', username='chacha20_ietf'), group_chat_created=False, link_preview_options=LinkPreviewOptions(is_disabled=True), message_id=886, supergroup_chat_created=False, text='/start\n/help\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👉本群正在清理僵尸，真人点我验证👈\n👁\u200d🗨请尽快验证,未验证用户会自动踢出哦👁\u200d🗨')`

**Comment by deus-developer** [comment]
Can you provide logs in debug mode? `logging.basicConfig(level=logging.DEBUG)`.

**Comment by KurimuzonAkuma** [comment]
Works fine for me
