### ISSUE TITLE
Отсутствует индекс на usernames.id

### ISSUE THREAD

**Issue by Bainky** [KurimuzonAkuma/pyrogram#70]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

из-за этого DELETE FROM usernames WHERE id = ? в update_peers крайне медленный, высокое потребление cpu

**Comment by ZeN220** [comment]
индексы только замедлят удаление записей
